name: upload-jar

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5.0.0

      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build Maven
        run: |
          apt-get update
          apt-get install -y maven
               
          mvn -B package --file pom.xml

      - name: Extract tag
        id: tag_name
        run: |
          tag_name="${{ github.ref_name }}"
          TAG_NAME="${tag_name%-*}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Upload Jar file to github release
        uses: softprops/action-gh-release@v2.4.1
        if: github.ref_type == 'tag'
        with:
          name: keycloak-otp-webhook-${{ steps.tag_name.outputs.TAG_NAME }}.jar
          files: target/keycloak-otp-webhook.jar
